language: cpp
sudo: required
script:
    - scripts/travis.sh
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            # Toolchain.
            - g++-7
            # Actual dependencies.
            - cmake
            # internal libgtest-dev has no dependencies
            - libxmlsec1-dev
            # internal libzip dependency
            - libbz2-dev
            # Needed by scripts/travis.sh only.
            - libnss3-tools
