language: cpp
script:
    - scripts/travis.sh
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            # Toolchain.
            - g++-7
            # Actual dependencies.
            - cmake
            # Internal xmlsec dependencies.
            - libnss3-dev
            - libxml2-dev
            # Internal libzip dependency.
            - libbz2-dev
            # Needed by scripts/travis.sh only.
            - libnss3-tools
