language: cpp
script:
    - scripts/travis.sh $DEBUG $WERROR --internal-libs
matrix:
  include:
  - name: "linux gcc release"
    env: DEBUG= WERROR=--werror
  - name: "linux gcc debug"
    env: DEBUG=--debug WERROR=--werror
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            # Toolchain.
            - g++-7
            # Actual dependencies.
            - cmake
            # Internal xmlsec dependencies.
            - libnss3-dev
            - libxml2-dev
            # Internal libzip dependency.
            - libbz2-dev
            # Needed by scripts/travis.sh only.
            - libnss3-tools
