language: cpp
sudo: required
script:
    - scripts/travis.sh
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            # Toolchain.
            - g++-7
            # Actual dependencies.
            - cmake
            - libgtest-dev
            - libxmlsec1-dev
            - libzip-dev
            # Needed by scripts/travis.sh only.
            - libnss3-tools
