version: "{build}"

os:
    - Visual Studio 2017

platform:
    - Win32

configuration:
    - Release

before_build:
    - cmake -H. -Bworkdir -DODFSIG_INTERNAL_LIBS=ON

build:
  project: workdir\odfsig.sln
  parallel: true
  verbosity: normal
